import { useRouter } from 'next/router'
import Head from 'next/head';
import Link from 'next/link';
import styles from './MainLayout.module.css'

import { Box, Button, Grid, Stack, Typography } from '@mui/material';
import { width } from '@mui/system';

interface LayoutProps {
    title?: string,
    children: React.ReactNode,
  }


const MainLayout = (props: LayoutProps) => {
    // const title: Props = props
    const router = useRouter();
    console.log('ROUTER', router);

    const { title, children } = props;
    return (
        <div>
            <Head>
                <title>{title} || Tecnical</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
      
            <nav className={styles.nav}>
                <Link href="/">
                    <a><h3><em>Tecnicl</em></h3></a>
                </Link>
                
                <div style={{display: 'flex'}}>
                <p className={styles.navItem}>Connect</p>
    
                <Link href="/about">
                <a className={styles.navItem}>About Us</a>
                </Link>
                </div>
            </nav>

            <main>
                {children}
            </main>
        </div>
    )
}

export default MainLayout;
