import { useRouter } from 'next/router'
import Head from 'next/head';
import Link from 'next/link';
import styles from './MainLayout.module.css'
import Image from 'next/image'

import ResponsiveDrawer from '../components/ResponsiveNavDrawer';

interface LayoutProps {
    title?: string,
    children: React.ReactNode,
  }


const MainLayout = (props: LayoutProps) => {
    // const title: Props = props
    const router = useRouter();

    const date = new Date(); 
    const year = date.getFullYear();

    const { title, children } = props;
    return (
        <div style={{
          minHeight: '100vh',
          display:'flex', 
          flexDirection:'column' ,
        }}>
            <Head>
                <title>{title} || Cascadian Software</title>
                <meta name="description" content="Generated by create next app" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <ResponsiveDrawer/>
         
            <main>
                {children}
            </main>

        <footer className={styles.footer}>
        <Link href="/contact">
        <a>
          Cascadian Software LLC &copy; {year}
          {/* Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
        </Link>
        <Link href="/privacy-policy">
          <a>
            Privacy Policy
          </a>
        </Link>
      </footer>
        </div>
    )
}

export default MainLayout;
