import { useRouter } from 'next/router'
import Head from 'next/head';
import Link from 'next/link';
import styles from './MainLayout.module.css'
import Image from 'next/image'


import { Box, Button, Grid, Stack, Typography } from '@mui/material';
import { width } from '@mui/system';
import ResponsiveDrawer from '../components/ResponsiveNavDrawer';

interface LayoutProps {
    title?: string,
    children: React.ReactNode,
  }


const MainLayout = (props: LayoutProps) => {
    // const title: Props = props
    const router = useRouter();
    console.log('ROUTER', router);

    const { title, children } = props;
    return (
        <div>
            <Head>
                <title>{title} || Tecnical</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ResponsiveDrawer/>
         
            <main>
                {children}
            </main>

        <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
        </div>
    )
}

export default MainLayout;
